// Generated Data Model

export struct AppData {
    temperature: float,
    humidity: float,
    pressure: float,
    wind-speed: float,
    wind-direction: float,
    feels-like: float,
    dew-point: float,
    uv-index: float,
    sensor-status: string,
    internet-status: string,
    forecast-data: string,
    temp-unit: string,
    wind-unit: string,
    pressure-unit: string,
    auto-refresh: bool,
    refresh-interval: float,
    location: string,
    last-update: string,
}
